apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blue
  labels:
    app: {{ printf "%s-%s" .Release.Name .Chart.Name | trunc 63 }}
    version: {{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ printf "%s-%s" .Release.Name .Chart.Name | trunc 63 }}
        version: {{ .Chart.Version }}
        release: {{ .Release.Name }}
        name: myapp
        color: blue
    spec:
      containers:
        - name: hello-world
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8080
              protocol: TCP

